language: node_js  #设置语言

dist: bionic

node_js: 10

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
  - export TZ='Asia/Shanghai' # 更改时区
  - cd .travis
  - gunzip travis.key.enc.gz
  - openssl aes-256-cbc -in travis.key.enc -out ~/.ssh/id_rsa -d -k CtbBnkohJFSW27ga 
  - cat ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent -s)
  - ssh-add
  - git config --global user.name 'ycwu314'
  - git config --global user.email '535215779@qq.com'

install:
#  - npm install

script:
  - hexo clean
  - hexo g
  - hexo d

branches:
  only:
    - hexo  

env:
 global:
   - GH_REF: github.com/ycwu314/ycwu314.github.io.git

addons:
  ssh_known_hosts:
    - gitee.com
    - github.com