language: node_js  #设置语言

dist: bionic

node_js: 10

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
  - git config --global user.name 'ycwu314'
  - git config --global user.email '535215779@qq.com'
  - export TZ='Asia/Shanghai' # 更改时区
  - cd .travis/
  - gunzip travis.key.enc.gz
  - openssl aes-256-cbc -in travis.key.enc -out ~/.ssh/id_rsa -d -k ${SSH_PWD} 
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent -s)
  - ssh-add
  - chmod u+x UpdateFile.py
  - unzip -P ${FONT_SECRET} secret_map.zip
  - mv secret_map.json ../
  - mv UpdateFile.py ../
  - cd ..
  - python3 UpdateFile.py source/_posts secret_map.json
  - sed -i "`grep -n neat_enable _config.yml | cut -d':' -f1`s/false/true/" _config.yml 

install:
  - npm install -g hexo --save
  - npm install hexo-lazyload-image --save
  - npm install hexo-neat --save
  - npm install hexo-autonofollow --save

script:
  - rm -f node_modules/hexo/lib/plugins/helper/open_graph.js 
  - cp .travis/open_graph.js node_modules/hexo/lib/plugins/helper/
  - hexo clean
  - hexo g
  - rm -f public/baidusitemap.xml public/atom.xml
  - hexo d

branches:
  only:
    - hexo  

env:
 global:

addons:
  ssh_known_hosts:
    - gitee.com
    - github.com