language: node_js  #设置语言

node_js: 10

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
    - export TZ='Asia/Shanghai' # 更改时区

install:
  - npm install -g hexo-cli

script:
  - hexo clean
  - hexo g
  - pwd
  - ls -al themes/next/source/lib

after_script:
  - cd ./public
  - git init
  - git config user.name "ycwu314"
  - git config user.email "535215779@qq.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master  #Travis_Token是在Travis中配置环境变量的名称

branches:
  only:
    - hexo  

env:
 global:
   - GH_REF: github.com/ycwu314/ycwu314.github.io.git  #设置GH_REF，注意更改yourname

