language: node_js  #设置语言

dist: bionic

node_js: 10

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
  - export TZ='Asia/Shanghai' # 更改时区
  - gunzip .travis/travis.key.enc.gz
  - openssl aes-256-cbc -in .travis/travis.key.enc -out ~/.ssh/id_rsa -d -k ${SSH_PWD} 
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent -s)
  - ssh-add
  - git config --global user.name 'ycwu314'
  - git config --global user.email '535215779@qq.com'
  - sed -i "`grep -n neat_enable _config.yml | cut -d':' -f1`s/false/true/" _config.yml

install:
  - npm install -g hexo --save
  - npm install hexo-lazyload-image --save
  - npm install hexo-neat --save
  - npm install hexo-autonofollow --save

script:
  - rm -f node_modules/hexo-lazyload-image/lib/default-image.json
  - cp .travis/default-image.json node_modules/hexo-lazyload-image/lib/
  - hexo clean
  - hexo g
  - rm -f public/baidusitemap.xml public/atom.xml
  - hexo d

branches:
  only:
    - hexo  

env:
 global:

addons:
  ssh_known_hosts:
    - gitee.com
    - github.com